// Generated by Copilot

/**
 * @typedef {Object} GameConfig
 * @property {number} CELL_SIZE - Size of each cell in pixels
 * @property {number} UPDATE_INTERVAL - Milliseconds between updates
 * @property {number} INITIAL_ALIVE_PROBABILITY - Probability of cell being alive
 */
export const GAME_CONFIG = {
    CELL_SIZE: 10,
    UPDATE_INTERVAL: 500,
    INITIAL_ALIVE_PROBABILITY: 0.3
};

/**
 * @typedef {Object} ColorTheme
 * @property {Object} COLORS - Color definitions for cell states
 */
export const THEME = {
    COLORS: {
        DEAD: '#ffffff',
        ALIVE: {
            LOW: '#9be9a8',    // 1-2 neighbors
            MEDIUM: '#40c463', // 3-4 neighbors
            HIGH: '#30a14e',   // 5-6 neighbors
            MAX: '#216e39'     // 7-8 neighbors
        }
    }
};
